name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.17.0
      - name: Setup package.json
        run: echo '{"name":"rescuetime-slack","version":"0.0.0","publishConfig":{"access":"public"},"scripts":{"semantic-release":"semantic-release"},"repository":{"type":"git","url":"https://github.com/AnandChowdhary/rescuetime-slack.git"},"author":"Anand Chowdhary <mail@anandchowdhary.com>","license":"MIT","bugs":{"url":"https://github.com/AnandChowdhary/rescuetime-slack/issues"},"homepage":"https://anandchowdhary.github.io/rescuetime-slack/","devDependencies":{"semantic-release":"^17.0.4","semantic-release-gitmoji":"^1.3.3"}}' > package.json
      - name: Install dependencies
        run: npm install
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
